# server
server:
  port: 8080
  servlet:
    context-path: /

#Spring
spring:
  application:
    name: MiTFM
  jackson:
    default-property-inclusion: NON_NULL
  datasource:
    url:  ${DB_URL} 
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
      
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
      

# OpenAI Service
openai-service:
  api-key: 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
  gpt-model: gpt-3.5-turbo
  audio-model: whisper-1
  http-client:
    read-timeout: 3000
    connect-timeout: 3000
  urls:
    base-url: https://api.openai.com/v1
    chat-url: /chat/completions
    create-transcription-url: /audio/transcriptions

# Management
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: 'ALWAYS'
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true

# Resilience4j
resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
resilience4j.ratelimiter:
  configs:
    instances:
      registerHealthIndicator: true
