# server
server:
  port: 8080
  servlet:
    context-path: /

#Spring
spring:
  application:
    name: MiTFM
  jackson:
    default-property-inclusion: NON_NULL
  datasource:
    url:  ${DB_URL} 
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB    
      location: /tmp/springboot-data/
  rabbitmq:
     host: ${RABBITMQ_HOST}
     port: 5672
     username: guest
     password: guest
      
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

# RabbitMQ
rabbitmq:
  queue:
    name: audio_queue
    exchange: audioExchange
    routing: 
      key: audioRoutinKey
      
# Management
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: 'ALWAYS'
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true

# Resilience4j
resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
resilience4j.ratelimiter:
  configs:
    instances:
      registerHealthIndicator: true
